### ISSUE TITLE
USER STORY: Log in/Log out

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/bookverse_unified#7]
As a **user** I want to **to log in and log out of the Bookverse** so that **I can access my account and protect my privacy**

## Acceptance Criteria

 * Users should be able to enter their username and password to log in
 * Users should have a "Logout" option that securely logs them out of their account
 * Upon successful login and logout, users should receive a confirmation message

## Tasks

- [x] Create a login page with input fields for username and password
- [x] Design a "Logout" button for users to log out from any page
- [x] Create an alert that show up when a user is successfully registered, logged in or logged out
